# Experiment Settings
experiment_name: "stage2_baseline"
device: "cuda"
seed: 42

# Data Settings
data:
  data_root: "/home/ruisi/mesh_compression/data/official"
  processed_dir: "/mnt/Lab/yeruisi/data/compression/dataset_preload"  # 预处理数据存放位置
  preprocessed_base_mesh_dir: "/mnt/Lab/yeruisi/data/compression/base_mesh_preload" # 预处理 Base Mesh 存放位置
  use_preprocess_base_mesh: True # 是否使用预处理的 Base Mesh
  point_num: 160000       # Encoder 输入的点云数量
  batch_size: 1
  num_workers: 16
  base_mesh_faces_min: 1000    # Base Mesh 目标面数范围
  base_mesh_faces_max: 3000
  simplification_backend: "pyfqmr" # "open3d" or "pyfqmr"

# Model Settings
model:
  feature_dim: 256        # Vertex Feature Dimension
  enc_hidden_dim: 128      # Encoder MLP Hidden Dim
  dec_hidden_dim: 128      # Decoder MLP Hidden Dim
  subdivision_levels: 8   # Positional Encoding Levels
  subdivision_rate: 8     # NGF Subdivision Rate (每条边细分段数)
  use_feature_transform: False
  predict_offset: False   # If True, predict 3D offset (xyz) in global coordinates instead of 1D displacement along normal

# Training Settings
train:
  epochs: 200
  lr: 1.0e-3
  weight_decay: 1.0e-5
  save_interval: 3       # Epochs
  log_interval: 10        # Steps
  
# Loss Weights
loss:
  use_chamfer: False       # Whether to use Chamfer Distance Loss (for debugging geometry)
  w_chamfer: 100.0
  w_render: 1.0           # Normal Consistency Loss
  w_laplacian: 0.0       # Mesh Smoothness
  w_disp: 0.0           # Displacement L2 Regularization
  w_mat: 0.001          # Feature Transform Regularization

# Renderer Settings
render:
  image_size: 512
  views_per_sample: 50     # 每个样本随机渲染的视角数
  dist_multiplier: 1.2

